<a href="https://colab.research.google.com/github/ataei0/DANA/blob/master/pre5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:

from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [7]:
from numpy import load

Data = load('/content/drive/MyDrive/Matrix Data/sparse_matrix.npz')
lst = Data.files
for item in lst:
    print(item)
    print(Data[item])

indices
[ 11103  31853  31854 ... 276253 368921 384959]
indptr
[        0       192       228 ... 113376415 113376545 113376558]
format
b'csr'
shape
[933095 398351]
data
[ 1.75086936 12.19738324 12.20355765 ... 18.7720261  34.64588635
 21.07869619]


In [8]:

from scipy import sparse
import numpy as np

temp_data = np.load('/content/drive/MyDrive/Matrix Data/sparse_matrix.npz')
M_data = sparse.csr_matrix((temp_data['data'], temp_data['indices'], temp_data['indptr']), shape = temp_data['shape']) 

In [3]:
!pip install sklearn

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
  Preparing metadata (setup.py) ... done
  Created wheel for sklearn: filename=sklearn-0.0.post1-py3-none-any.whl size=2344 sha256=d9711b722e0bfdd8d6d65ca6809fd911ffbf57afaf02c36f74b767a68f76d828
  Stored in directory: /root/.cache/pip/wheels/14/25/f7/1cc0956978ae479e75140219088deb7a36f60459df242b1a72
Successfully built sklearn


In [10]:
import scipy.sparse
from sklearn import *
from sklearn.preprocessing import normalize
#normalizing data over columns:
M_data_normalized_C = normalize(M_data, norm='l1', axis=0)
sparse.save_npz("data_normalized_C.npz", scipy.sparse.csr_matrix(M_data_normalized_C))
#normalizing data over rows:
M_data_normalized_R = normalize(M_data, norm='l1', axis=1)

In [ ]:

from scipy.sparse import csr_matrix
print(csr_matrix(M_data_normalized_C.getcol(76454)))

  (14934, 0)	0.03515021992374439
  (70153, 0)	0.021820576828983265
  (87521, 0)	0.010194105201996652
  (178045, 0)	0.10129099121922339
  (191205, 0)	0.003980258091772798
  (199286, 0)	0.018018729166719993
  (272219, 0)	0.020423018309388842
  (322829, 0)	0.33682884892381654
  (337739, 0)	0.04646005398316955
  (347354, 0)	0.012683272279241707
  (474496, 0)	0.3181580240625511
  (475116, 0)	0.007183232565226506
  (594389, 0)	0.04254290903916482
  (724324, 0)	0.014715637516529496
  (845638, 0)	0.010550122888470913


In [12]:
#normalizing over both columns and rows:
temp = M_data_normalized_C.multiply(M_data_normalized_R)
M_data_normalized_RC = temp.sqrt()
sparse.save_npz("data_normalized_RC.npz", scipy.sparse.csr_matrix(M_data_normalized_RC))

In [ ]:
import sklearn.metrics

data = M_data_normalized_RC.transpose()
ind_col = [i for i in range(20000)]  #398351 
data0 = data[ind_col,:]
res = sklearn.metrics.pairwise_distances(data0, data0, metric = 'euclidean')
res
# taken time for 10000 : 2s
# taken time for 20000 : 6s
# RAM limitations for  30k 

In [3]:
from sklearn import random_projection
from sklearn.random_projection import johnson_lindenstrauss_min_dim
#min required rows
min_dim = johnson_lindenstrauss_min_dim(n_samples=398351, eps=0.08)
min_dim

17026

In [ ]:
data = M_data_normalized_RC.transpose()
transformer = random_projection.SparseRandomProjection(n_components=11052)
data_shrinked = transformer.fit_transform(data)
data_shrinked.shape

(398351, 11052)

In [ ]:
sparse.save_npz("shrinled.npz", data_shrinked)

In [ ]:
from numpy import load

Data = load('/content/drive/MyDrive/shrinled.npz')
lst = Data.files
for item in lst:
    print(item)
    print(Data[item])

indices
[9735 9066 8755 ... 5365 4392 3534]
indptr
[        0      1649     12701 ... 321183640 321183647 321183654]
format
b'csr'
shape
[398351  11052]
data
[-0.00166834 -0.00166834 -0.00166834 ...  0.05626455  0.05626455
  0.05626455]


In [3]:
from scipy import sparse
import numpy as np

temp_data = np.load('/content/drive/MyDrive/shrinled.npz')
S_data = sparse.csr_matrix((temp_data['data'], temp_data['indices'], temp_data['indptr']), shape = temp_data['shape']) 

In [ ]:
from scipy.sparse import csr_matrix
print(csr_matrix(S_data.getrow(10000)))

  (0, 10854)	-0.0013073145454501958
  (0, 9742)	0.0013073145454501958
  (0, 9611)	-0.0013073145454501958
  (0, 8938)	-0.0013073145454501958
  (0, 8929)	0.0013073145454501958
  (0, 8671)	-0.0013073145454501958
  (0, 7562)	0.0013073145454501958
  (0, 7394)	0.0013073145454501958
  (0, 7381)	-0.0013073145454501958
  (0, 5751)	-0.0013073145454501958
  (0, 5091)	0.0013073145454501958
  (0, 4316)	0.0013073145454501958
  (0, 4232)	0.0013073145454501958
  (0, 3409)	0.0013073145454501958
  (0, 3367)	0.0013073145454501958
  (0, 665)	0.0013073145454501958
  (0, 167)	0.0013073145454501958
  (0, 10145)	0.0018344756791523601
  (0, 7925)	0.0018344756791523601
  (0, 7668)	0.0018344756791523601
  (0, 6543)	-0.0018344756791523601
  (0, 4331)	-0.0018344756791523601
  (0, 4317)	-0.0018344756791523601
  (0, 3456)	0.0018344756791523601
  (0, 2167)	0.0018344756791523601
  :	:
  (0, 1339)	0.05706025572643857
  (0, 10443)	-0.0012846990107683138
  (0, 10432)	0.0012846990107683138
  (0, 10130)	0.00128469901076831

In [ ]:
import sklearn.metrics

#data = M_data_normalized_RC.transpose()
#ind_col = [i for i in range(20000)]  #398351 
#data0 = S_data[ind_col,:]
res = sklearn.metrics.pairwise_distances(S_data, S_data, metric = 'euclidean')
res

In [1]:
from scipy import sparse
import numpy as np

temp_data = np.load('/content/drive/MyDrive/data_normalized_RC.npz')
RC = sparse.csr_matrix((temp_data['data'], temp_data['indices'], temp_data['indptr']), shape = temp_data['shape']) 

In [9]:
from sklearn import *
from sklearn.decomposition import PCA as RandomizedPCA
pca_data = RandomizedPCA(n_components=min_dim, svd_solver='randomized', whiten=True).fit(RC.transpose())


TypeError: ignored

In [ ]:
from sklearn.decomposition import TruncatedSVD
from scipy import sparse as sp

clf = TruncatedSVD(17026)
Xpca = clf.fit_transform(RC.transpose())

In [ ]:
from sklearn.decomposition import SparsePCA
 
transformer = SparsePCA(n_components=17026, random_state=0)
transformer.fit((RC.transpose()).toarray())

X_transformed = transformer.transform(RC.transpose())
X_transformed.shape


In [ ]:
threshold = 0.05
res[res>threshold] = 0
above_threshold = res >= v["threshold"]
